import logging
from pathlib import Path
import sys

# TODO: decide whether ultralytics or roboflow
from ultralytics import RTDETR
from ultralytics import YOLO
import yaml

from research.src.models.training import DetectorTrainerConfig

logger = logging.getLogger(__name__)


def run_detector_training(config_path: Path):
    """
    Trains the Student Model (RT-DETR or YOLO) using the dataset
    generated by the (Distillation) pipeline.
    """

    logger.info(f"Loading detector config from {config_path}")
    with open(config_path) as f:
        raw_config = yaml.safe_load(f)
    try:
        config = DetectorTrainerConfig(**raw_config)
        logger.info(f"Config loaded: {config.model_dump()}")
    except Exception as e:
        logger.error(f"Config Validation Failed: {e}")
        sys.exit(1)

    model_name = config.base_model if config.base_model else "rtdetr-l.pt"
    logger.info(f"Loading model architecture: {model_name}")

    if "rtdetr" in model_name.lower().strip():
        model = RTDETR(model_name)
    else:
        model = YOLO(model_name)

    logger.info(f"Starting training on dataset: {config.dataset_yaml}")

    try:
        results = model.train(
            data=str(config.dataset_yaml),
            project=config.project_name,
            name="run",
            epochs=config.epochs,
            imgsz=config.imgsz,
            batch=config.batch_size,
            device=config.device,
            optimizer=config.optimizer,
            lr0=config.lr0,
            exist_ok=True,  # Overwrite previous run
            plots=True,  # Generate CM automatically
            val=True,
        )
    except Exception as e:
        logger.error(f"Training Failed: {e}")
        sys.exit(1)

    logger.info("Exporting to ONNX for Server Deployment...")
    try:
        export_path = model.export(format="onnx", dynamic=True)
        logger.info(f"Model exported successfully to: {export_path}")
    except Exception as e:
        logger.warning(f"ONNX Export failed (You can still use .pt): {e}")

    logger.info(
        f"Training Pipeline Complete. Check {config.project_name}/run for charts."
    )
    return results
